{ inputs, lib, pkgs, ... }:

let
  theme = import ./theme.nix { inherit inputs; };
  c = theme.colors;
  scripts = import ./scripts.nix { inherit pkgs; };

  apply-wallpaper = pkgs.writeShellApplication {
    name = "apply-wallpaper";
    runtimeInputs = with pkgs; [
      awww
      coreutils
      scripts.display-refresh-rate
    ];
    text = ''
      for _ in {1..30}; do
        awww query >/dev/null 2>&1 && break
        sleep 0.1
      done

      exec awww img ${lib.escapeShellArg theme.wallpaper} \
        --resize crop \
        --crop-gravity center \
        --transition-type fade \
        --transition-duration 1 \
        --transition-fps "$(display-refresh-rate)"
    '';
  };

  desktopShellAutostart = ''
    hl.exec_cmd("${apply-wallpaper}/bin/apply-wallpaper")
  '';
in
{
  home.activation.removeAutogeneratedHyprlandStub =
    lib.hm.dag.entryBefore [ "checkLinkTargets" ] ''
      legacy_config="$HOME/.config/hypr/hyprland.conf"

      if [[ -f "$legacy_config" && ! -L "$legacy_config" ]] \
        && ${pkgs.gnugrep}/bin/grep -q '^# This config is a STUB!' "$legacy_config"; then
        $DRY_RUN_CMD ${pkgs.coreutils}/bin/rm -f "$legacy_config"
      fi
    '';

  wayland.windowManager.hyprland = {
    enable = true;
    package = null;
    portalPackage = null;
    configType = "lua";
    systemd.enable = true;
    systemd.enableXdgAutostart = true;
    extraLuaFiles."config" = builtins.replaceStrings
      [
        "@POLKIT_AGENT@"
        "@DESKTOP_SHELL_AUTOSTART@"
        "@ACTIVE_BORDER@"
        "@ACTIVE_BORDER_ALT@"
        "@INACTIVE_BORDER@"
        "@SHADOW@"
      ]
      [
        "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1"
        desktopShellAutostart
        c.accent
        c.yellow
        c.muted
        c.background
      ]
      (builtins.readFile ./hyprland.lua);

    settings = {
      # The actual configuration is kept in hyprland.lua. Home Manager writes
      # and loads it from the generated hyprland.lua entry point.
    };
  };

  programs.hyprlock = {
    enable = true;
    settings = {
      general = {
        disable_loading_bar = true;
        hide_cursor = true;
        grace = 2;
      };
      background = {
        monitor = "";
        color = "rgba(${c.background}ff)";
        blur_passes = 3;
        blur_size = 8;
      };
      input-field = {
        monitor = "";
        size = "300, 56";
        outline_thickness = 2;
        dots_size = 0.25;
        dots_spacing = 0.25;
        outer_color = "rgba(${c.accent}ff)";
        inner_color = "rgba(${c.surface}ee)";
        font_color = "rgba(${c.foreground}ff)";
        fade_on_empty = false;
        placeholder_text = "<i>Hasło…</i>";
        position = "0, -80";
        halign = "center";
        valign = "center";
      };
      label = {
        monitor = "";
        text = "cmd[update:1000] echo \"$(date +'%H:%M')\"";
        color = "rgba(${c.foreground}ff)";
        font_size = 72;
        font_family = "${theme.fonts.monospace} Bold";
        position = "0, 80";
        halign = "center";
        valign = "center";
      };
    };
  };

  services.awww.enable = true;

  services.hypridle = {
    enable = true;
    settings = {
      general = {
        lock_cmd = "pidof hyprlock || hyprlock";
        before_sleep_cmd = "loginctl lock-session";
        after_sleep_cmd = "hyprctl dispatch dpms on";
      };
      listener = [
        {
          timeout = 240;
          on-timeout = "pidof hyprlock || screensaver";
          on-resume = "pkill -f '[o]rg.polamaniec.screensaver'";
        }
        {
          timeout = 300;
          on-timeout = "loginctl lock-session";
        }
        {
          timeout = 330;
          on-timeout = "hyprctl dispatch dpms off";
          on-resume = "hyprctl dispatch dpms on";
        }
        {
          timeout = 1800;
          on-timeout = "systemctl suspend";
        }
      ];
    };
  };

}
